/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.LoginController;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import vista.LoginFrame;
import vista.MainMenuFrame;

/**
 *
 * @author admin
 */
public class FrmDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FrmAeronave1
     */
    public FrmDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminarAero = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminarTripulacion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnTripulacion = new javax.swing.JButton();
        btnEditarTripulacion1 = new javax.swing.JButton();
        btnOperaciones1 = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AIRWAYS");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 70, 10));

        btnEliminarAero.setBackground(new java.awt.Color(0, 51, 102));
        btnEliminarAero.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarAero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        btnEliminarAero.setText("Eliminar aeronave");
        btnEliminarAero.setBorder(null);
        btnEliminarAero.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEliminarAero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAeroActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarAero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, -1));

        btnDashboard.setBackground(new java.awt.Color(0, 51, 102));
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, -1));

        btnRegistrar.setBackground(new java.awt.Color(0, 51, 102));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        btnRegistrar.setText("Registrar aeronave");
        btnRegistrar.setBorder(null);
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        btnEditar.setBackground(new java.awt.Color(0, 51, 102));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        btnEditar.setText("Editar aeronave");
        btnEditar.setBorder(null);
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, -1));

        btnEliminarTripulacion.setBackground(new java.awt.Color(0, 51, 102));
        btnEliminarTripulacion.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarTripulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        btnEliminarTripulacion.setText("Eliminar tripulación");
        btnEliminarTripulacion.setBorder(null);
        btnEliminarTripulacion.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEliminarTripulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTripulacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SKYLINE");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, 20));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 102, 204));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 120, 30));

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 102, 204));
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 120, 30));

        btnTripulacion.setBackground(new java.awt.Color(0, 51, 102));
        btnTripulacion.setForeground(new java.awt.Color(255, 255, 255));
        btnTripulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        btnTripulacion.setText("Registrar tripulación");
        btnTripulacion.setBorder(null);
        btnTripulacion.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnTripulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTripulacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));

        btnEditarTripulacion1.setBackground(new java.awt.Color(0, 51, 102));
        btnEditarTripulacion1.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarTripulacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        btnEditarTripulacion1.setText("Editar tripulación");
        btnEditarTripulacion1.setBorder(null);
        btnEditarTripulacion1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEditarTripulacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTripulacion1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarTripulacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        btnOperaciones1.setBackground(new java.awt.Color(0, 51, 102));
        btnOperaciones1.setForeground(new java.awt.Color(255, 255, 255));
        btnOperaciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        btnOperaciones1.setText("Operaciones");
        btnOperaciones1.setBorder(null);
        btnOperaciones1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnOperaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperaciones1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOperaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 490));

        content.setBackground(new java.awt.Color(225, 238, 250));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        jLabel4.setText("AIRWAYS");
        jLabel4.setToolTipText("");
        content.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 70, 10));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setText("SKYLINE");
        jLabel8.setToolTipText("");
        content.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 40, 40));

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 740, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        MainMenuFrame main = new MainMenuFrame();
            main.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cerrarSesion() {
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres cerrar sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            LoginController.cerrarSesion(); 

            this.dispose();

            LoginFrame login = new LoginFrame();
            login.setVisible(true);
        }
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        JPanelRegistrarAeronave aero = new JPanelRegistrarAeronave();
        showPanel(aero);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        JPanelEditarAeronave aero = new JPanelEditarAeronave();
        showPanel(aero);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEliminarTripulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTripulacionActionPerformed
        JPanelEditarTripulación trip = new JPanelEditarTripulación();
        showPanel(trip);
    }//GEN-LAST:event_btnEliminarTripulacionActionPerformed

    private void btnEliminarAeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAeroActionPerformed
        JPanelEliminarAeronave eliminar = new JPanelEliminarAeronave();
        showPanel(eliminar);
    }//GEN-LAST:event_btnEliminarAeroActionPerformed

    private void btnTripulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTripulacionActionPerformed
        JPanelRegistrarTripulación trip = new JPanelRegistrarTripulación();
        showPanel(trip);
    }//GEN-LAST:event_btnTripulacionActionPerformed

    private void btnEditarTripulacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTripulacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarTripulacion1ActionPerformed

    private void btnOperaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperaciones1ActionPerformed
        JPanelAsignarTripulante asignar = new JPanelAsignarTripulante();
        showPanel(asignar);
    }//GEN-LAST:event_btnOperaciones1ActionPerformed

    private void showPanel(JPanel p){
        p.setSize(760, 490);
        p.setLocation(160,0);
        
        content.removeAll();
        content.add(
                p,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(
                        0,
                        0,
                        760, 
                        490
                )
        );
        content.revalidate();
        content.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarTripulacion1;
    private javax.swing.JButton btnEliminarAero;
    private javax.swing.JButton btnEliminarTripulacion;
    private javax.swing.JButton btnOperaciones1;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnTripulacion;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
