/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import controlador.ReservaController;
import Modelo.Reserva;
import controlador.LoginController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

/**
 *
 * @author admin
 */
public class JPanelConsultarReservas extends javax.swing.JPanel {

    Cliente cliente = LoginController.getClienteActual();
    private ReservaController reservaController = new ReservaController();
    private DefaultTableModel modeloTabla;
    private boolean cargandoCombos = true;

    /**
     * Creates new form JPanelAeronave
     */
    public JPanelConsultarReservas() {
        initComponents();
        txtusuario.setText(
                " " + cliente.getNombres() + " " + cliente.getApellidos()
        );

        cargarReservas();
        cargarCombos();
        eventosCombos();

        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {

                if (txtBuscador.getText().trim().isEmpty()) {

                    cargarReservas();

                }

            }
        });
    }

    private void cargarCombos() {

        cargandoCombos = true;

        cbxRuta.removeAllItems();
        cbxEstado.removeAllItems();
        cbxFecha.removeAllItems();

        cbxRuta.addItem("Todos");
        cbxEstado.addItem("Todos");
        cbxFecha.addItem("Todas");

        for (String ruta : reservaController.obtenerRutas(cliente.getId())) {
            cbxRuta.addItem(ruta);
        }

        for (String estado : reservaController.obtenerEstados(cliente.getId())) {
            cbxEstado.addItem(estado);
        }

        for (String fecha : reservaController.obtenerFechas(cliente.getId())) {
            cbxFecha.addItem(fecha);
        }
        cargandoCombos = false;

    }

    private void eventosCombos() {

        cbxRuta.addActionListener(e -> {

            if (!cargandoCombos) {
                filtrarReservas();
            }

        });

        cbxEstado.addActionListener(e -> {

            if (!cargandoCombos) {
                filtrarReservas();
            }

        });

        cbxFecha.addActionListener(e -> {

            if (!cargandoCombos) {
                filtrarReservas();
            }

        });

    }

    private void mostrarReservas(List<Reserva> lista) {

        modeloTabla.setRowCount(0);

        for (Reserva r : lista) {

            modeloTabla.addRow(new Object[]{
                r.getIdReserva(),
                r.getRuta(),
                r.getFechaReserva(),
                r.getCantidadPasajeros(),
                r.getTotal(),
                r.getEstado(),
                r.getAsiento()
            });

        }

    }

    private void cargarReservas() {

        if (modeloTabla == null) {

            modeloTabla = new DefaultTableModel();

            modeloTabla.setColumnIdentifiers(new Object[]{
                "Reserva",
                "Ruta",
                "Fecha",
                "Pasajeros",
                "Total",
                "Estado",
                "Asiento"
            });

            tableReservas.setModel(modeloTabla);

        }

        mostrarReservas(
                reservaController.listarReservas(cliente.getId())
        );
    }

    private void filtrarReservas() {

        String ruta
                = cbxRuta.getSelectedItem().toString();

        String estado
                = cbxEstado.getSelectedItem().toString();

        String fecha
                = cbxFecha.getSelectedItem().toString();

        List<Reserva> lista
                = reservaController.filtrarReservas(
                        cliente.getId(),
                        ruta,
                        estado,
                        fecha
                );
        mostrarReservas(lista);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtusuario = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableReservas = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        cbxFecha = new javax.swing.JComboBox<>();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cbxRuta = new javax.swing.JComboBox<>();
        txtBuscador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(225, 238, 250));

        txtusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile.png"))); // NOI18N
        txtusuario.setText("Usuario");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel9.setText("CONSULTAR RESERVAS POR ORIGEN-DESTINO-ESTADO-ASIENTO");
        jLabel9.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(225, 238, 250));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/setting.png"))); // NOI18N
        jButton1.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 102));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Reserva", "Ruta", "Fecha", "Pasajeros", "Total", "Estado", "Asiento"
            }
        ));
        jScrollPane2.setViewportView(tableReservas);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 820, 370));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel11.setText("FILTROS:");
        jLabel11.setToolTipText("");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 60, 20));

        cbxFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cbxFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 70, -1));

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 70, -1));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel20.setText("Fecha");
        jLabel20.setToolTipText("");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 50, -1));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel22.setText("Ruta");
        jLabel22.setToolTipText("");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 50, -1));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel24.setText("Estado");
        jLabel24.setToolTipText("");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 50, -1));

        cbxRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cbxRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 70, -1));

        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyPressed(evt);
            }
        });
        jPanel3.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 370, 40));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 40, 40));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel13.setText("BUSCAR: ");
        jLabel13.setToolTipText("");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtusuario))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarReserva() {

        String criterio = txtBuscador.getText().trim();

        if (criterio.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un criterio de búsqueda"
            );

            return;
        }

        List<Reserva> lista = reservaController.buscarReservas(cliente.getId(), criterio);

        if (lista.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se encontraron resultados"
            );

            return;
        }
        mostrarReservas(lista);

    }
    private void txtBuscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            buscarReserva();
        }
    }//GEN-LAST:event_txtBuscadorKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarReserva();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxFecha;
    private javax.swing.JComboBox<String> cbxRuta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tableReservas;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JLabel txtusuario;
    // End of variables declaration//GEN-END:variables
}
